//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacioni_per_menaxhimin_e_çerdhes_se_femijeve {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gjuhaAl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gjuhaAl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplikacioni_per_menaxhimin_e_çerdhes_se_femijeve.gjuhaAl", typeof(gjuhaAl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITO.
        /// </summary>
        internal static string bEdito {
            get {
                return ResourceManager.GetString("bEdito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHKYCU.
        /// </summary>
        internal static string bexit {
            get {
                return ResourceManager.GetString("bexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEMIJET.
        /// </summary>
        internal static string bFemijet {
            get {
                return ResourceManager.GetString("bFemijet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLASET.
        /// </summary>
        internal static string bKlase {
            get {
                return ResourceManager.GetString("bKlase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-1.
        /// </summary>
        internal static string blabeli1 {
            get {
                return ResourceManager.GetString("blabeli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-2.
        /// </summary>
        internal static string blabeli2 {
            get {
                return ResourceManager.GetString("blabeli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-3.
        /// </summary>
        internal static string blabeli3 {
            get {
                return ResourceManager.GetString("blabeli3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-4.
        /// </summary>
        internal static string blabeli4 {
            get {
                return ResourceManager.GetString("blabeli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-1.
        /// </summary>
        internal static string blabeli5 {
            get {
                return ResourceManager.GetString("blabeli5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-2.
        /// </summary>
        internal static string blabeli6 {
            get {
                return ResourceManager.GetString("blabeli6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-3.
        /// </summary>
        internal static string blabeli7 {
            get {
                return ResourceManager.GetString("blabeli7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa A-4.
        /// </summary>
        internal static string blabeli8 {
            get {
                return ResourceManager.GetString("blabeli8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXO.
        /// </summary>
        internal static string bLexo {
            get {
                return ResourceManager.GetString("bLexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESUESIT.
        /// </summary>
        internal static string bMesuesit {
            get {
                return ResourceManager.GetString("bMesuesit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGESAT.
        /// </summary>
        internal static string bPagesat {
            get {
                return ResourceManager.GetString("bPagesat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETRAT.
        /// </summary>
        internal static string bParametrat {
            get {
                return ResourceManager.GetString("bParametrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RREGULLIMI.
        /// </summary>
        internal static string brregullimi {
            get {
                return ResourceManager.GetString("brregullimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHTO.
        /// </summary>
        internal static string bShto {
            get {
                return ResourceManager.GetString("bShto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miresevini :.
        /// </summary>
        internal static string lEmriMbiemri {
            get {
                return ResourceManager.GetString("lEmriMbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suksesi i përgjithshëm i Klasëve Janar-Mars.
        /// </summary>
        internal static string lPaneli1 {
            get {
                return ResourceManager.GetString("lPaneli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporti i mungesave javore.
        /// </summary>
        internal static string lPaneli2 {
            get {
                return ResourceManager.GetString("lPaneli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedh Gjuhen :.
        /// </summary>
        internal static string lZgjedhGjuhen {
            get {
                return ResourceManager.GetString("lZgjedhGjuhen", resourceCulture);
            }
        }
    }
}
